# Generated by Django 4.2.16 on 2024-12-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_email_address_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userverification',
            old_name='user',
            new_name='email',
        ),
    ]
