# Generated by Django 4.1.3 on 2024-12-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_fullname_user_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullName',
            new_name='username',
        ),
    ]
